version: "3.4"

services:
  ingress:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/docker/Dockerfile.ingress
    links:
      - influxdb:api
      - client
    ports:
      - 8080:80
      - 8443:443

  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-alpha
    volumes:
      - ./.persist/influxdb:/var/lib/influxdb2
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt

  client:
    image: quay.io/aboatwright/influxdb-ui-dev
    environment:
      - NODE_ENV=development
    volumes:
      - ${PROJECT_ROOT}/src:/repo/src:delegated
      - ${PROJECT_ROOT}/assets:/repo/assets:delegated
      - ${SWAGGER_FILE}:/http/swagger.yml
      - ${GIT_FOLDER}:/repo/.git

